[tool.poetry]
name = "slacklogger"
version = "0.1.0"
description = ""
authors = ["tomiwa-dev <adewoletomiwa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
slack-sdk = "^3.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
